spring.application.name=crudapp
spring.config.import=optional:file:.env[.properties]
# በፎቶው ላይ በሚታየው External Access መሠረት የተስተካከለ የ JDBC መስመር
spring.datasource.url=jdbc:postgresql://db.aletcloud.com:54334/boot
spring.datasource.username=admin_boot
spring.datasource.password=zF6ruNOZiL64WCP:macX:zh-4GE9KiDj
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate ማስተካከያ
spring.jpa.hibernate.ddl-auto=update

# --- DATABASE CONNECTION LOGS IN DETAIL ---
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.com.zaxxer.hikari=DEBUG
# --- ከ8080 ወደ 8081 ተቀይሯል
 const API_URL = process.env.REACT_APP_API_URL || "http://localhost:8081/api/tasks";
#const API_URL = process.env.REACT_APP_API_URL || "https://spring.app.aletcloud.com/api/tasks";
server.port=8081

